version: "3.8"

services:
  db:
    image: postgres
    container_name: autouni-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: autouni
      POSTGRES_USER: postgres
      POSTGRES_DB: autounidb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
