services:
  - type: web
    name: autouni-backend    env: node
    buildCommand: npm install && npm run build && npm run db:deploy
    startCommand: bash ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
    plan: free
    healthCheckPath: /