services:
  - type: web
    name: autouni-backend    env: docker
    dockerfilePath: ./Dockerfile.simple
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
    plan: free
    healthCheckPath: /
